-- ============================================================
-- CognaSync — Medication Reference v2 Migration
-- Run once in Supabase > SQL Editor
-- Safe to re-run (ON CONFLICT (name) DO UPDATE)
-- ============================================================
-- Adds new columns:
--   purpose              TEXT  – plain-language description of the drug
--   conditions_treated   TEXT  – comma-separated indications
--   dosage_range         TEXT  – typical range for reference only
--   discontinuation_notes TEXT – what to expect when stopping
--   common_doses_list    JSONB – array of dose strings for UI chips
-- ============================================================

-- 1. Ensure table exists with base columns (creates it if missing)
CREATE TABLE IF NOT EXISTS medication_reference (
  id                    BIGSERIAL PRIMARY KEY,
  name                  TEXT NOT NULL,
  category              TEXT,
  common_dose           NUMERIC,
  dose_unit             TEXT DEFAULT 'mg',
  typical_onset_hours   NUMERIC,
  common_side_effects   JSONB,
  notes                 TEXT
);

-- 2. Add unique constraint if missing
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'medication_reference'::regclass AND contype = 'u'
      AND conname = 'medication_reference_name_key'
  ) THEN
    ALTER TABLE medication_reference ADD CONSTRAINT medication_reference_name_key UNIQUE (name);
  END IF;
END $$;

-- 3. Add new columns if missing
ALTER TABLE medication_reference
  ADD COLUMN IF NOT EXISTS purpose TEXT,
  ADD COLUMN IF NOT EXISTS conditions_treated TEXT,
  ADD COLUMN IF NOT EXISTS dosage_range TEXT,
  ADD COLUMN IF NOT EXISTS discontinuation_notes TEXT,
  ADD COLUMN IF NOT EXISTS common_doses_list JSONB;

-- ============================================================
-- 4. Seed all medications
--    ON CONFLICT DO UPDATE ensures re-runs are safe and
--    backfill new columns into existing rows
-- ============================================================

INSERT INTO medication_reference
  (name, category, common_dose, dose_unit, typical_onset_hours,
   common_side_effects, notes,
   purpose, conditions_treated, dosage_range,
   discontinuation_notes, common_doses_list)
VALUES

-- ── SSRIs ──────────────────────────────────────────────────────────────────
('sertraline', 'SSRI', 50, 'mg', 336,
 ARRAY['nausea','insomnia','sexual dysfunction','diarrhea','dry mouth','dizziness','fatigue'],
 'Avoid with MAOIs (serotonin syndrome). Use caution with tramadol, lithium, triptans, and anticoagulants.',
 'An SSRI that increases serotonin availability in the brain. One of the most commonly prescribed antidepressants.',
 'Depression, generalized anxiety disorder, panic disorder, OCD, PTSD, social anxiety disorder, PMDD',
 '25–200 mg/day, once daily. Most start at 25–50 mg; typical maintenance 50–150 mg.',
 'Taper gradually when stopping. Abrupt discontinuation may cause dizziness, nausea, irritability, sensory disturbances ("brain zaps"), and flu-like symptoms.',
 '["25 mg", "50 mg", "100 mg", "150 mg", "200 mg"]'::jsonb),

('fluoxetine', 'SSRI', 20, 'mg', 336,
 ARRAY['nausea','insomnia','sexual dysfunction','anxiety','headache','dry mouth','diarrhea'],
 'Very long half-life (~5 days). Strong CYP2D6 inhibitor — raises levels of many co-medications. 5-week washout required before MAOI. Avoid MAOIs.',
 'Long-acting SSRI notable for its 5-day half-life, which makes discontinuation symptoms uncommon. Strong inhibitor of several liver enzymes.',
 'Depression, OCD, panic disorder, bulimia nervosa, PMDD, bipolar depression (adjunct)',
 '10–80 mg/day, once daily (usually morning). Typical dose 20–40 mg.',
 'Lowest discontinuation syndrome risk of any antidepressant due to very long half-life. Gradual taper still preferred when stopping.',
 '["10 mg", "20 mg", "40 mg", "60 mg", "80 mg"]'::jsonb),

('escitalopram', 'SSRI', 10, 'mg', 336,
 ARRAY['nausea','insomnia','sexual dysfunction','fatigue','dry mouth','sweating','diarrhea'],
 'Dose-dependent QT prolongation — avoid other QT-prolonging drugs and high doses in elderly. Fewer CYP interactions than other SSRIs. Avoid MAOIs.',
 'Highly selective SSRI with a favorable side-effect and drug-interaction profile. Often considered first-line.',
 'Depression, generalized anxiety disorder, panic disorder, social anxiety disorder, OCD',
 '5–20 mg/day, once daily. Max 10 mg/day in elderly or hepatic impairment.',
 'Taper slowly when stopping. Risk of dizziness, nausea, and sensory disturbances with abrupt discontinuation.',
 '["5 mg", "10 mg", "20 mg"]'::jsonb),

('citalopram', 'SSRI', 20, 'mg', 336,
 ARRAY['nausea','dry mouth','sweating','fatigue','insomnia','sexual dysfunction'],
 'Max 20 mg/day if age >60 or hepatic impairment (QT prolongation risk). Avoid other QT-prolonging agents. Avoid MAOIs.',
 'SSRI with dose-dependent QT prolongation risk. Useful in elderly patients at low doses due to minimal drug interactions.',
 'Depression, panic disorder, OCD, social anxiety disorder',
 '10–40 mg/day (max 20 mg in elderly/hepatic impairment), once daily.',
 'Taper gradually. Discontinuation may cause dizziness, nausea, irritability, and sensory disturbances.',
 '["10 mg", "20 mg", "40 mg"]'::jsonb),

('paroxetine', 'SSRI', 20, 'mg', 336,
 ARRAY['nausea','sedation','weight gain','sexual dysfunction','constipation','dry mouth','discontinuation syndrome'],
 'Strong CYP2D6 inhibitor. Short half-life — high discontinuation syndrome risk; taper slowly. Teratogenic risk. Avoid MAOIs.',
 'Sedating SSRI with anticholinergic properties. Shortest half-life in its class, making discontinuation syndrome more likely than with other SSRIs.',
 'Depression, OCD, panic disorder, social anxiety disorder, PTSD, GAD, PMDD',
 '10–60 mg/day, once daily (often at bedtime due to sedation).',
 'HIGH discontinuation risk — taper very slowly (weeks to months). Abrupt stopping commonly causes severe dizziness, nausea, sensory disturbances, agitation, and rebound anxiety.',
 '["10 mg", "20 mg", "30 mg", "40 mg"]'::jsonb),

('fluvoxamine', 'SSRI', 100, 'mg', 336,
 ARRAY['nausea','insomnia','sedation','sexual dysfunction','dry mouth'],
 'Potent CYP1A2 and CYP3A4 inhibitor — markedly raises levels of clozapine, theophylline, tizanidine, and caffeine. Avoid MAOIs.',
 'SSRI primarily used for OCD. Potent inhibitor of multiple liver enzymes — significant drug interaction risk.',
 'OCD, social anxiety disorder, depression',
 '50–300 mg/day; doses above 100 mg typically split twice daily.',
 'Taper gradually. Discontinuation symptoms include dizziness, nausea, and irritability.',
 '["50 mg", "100 mg", "150 mg", "200 mg"]'::jsonb),

('vilazodone', 'SSRI / 5-HT1A partial agonist', 20, 'mg', 336,
 ARRAY['diarrhea','nausea','insomnia','dry mouth','dizziness','sexual dysfunction'],
 'Take with food to increase absorption. Avoid MAOIs. CYP3A4 substrate.',
 'Combines serotonin reuptake inhibition with partial serotonin receptor agonism. May have lower sexual side effects than standard SSRIs.',
 'Depression, generalized anxiety disorder',
 '10–40 mg/day, once daily with food.',
 'Taper when stopping. Discontinuation symptoms similar to other SSRIs.',
 '["10 mg", "20 mg", "40 mg"]'::jsonb),

('vortioxetine', 'Serotonin modulator', 10, 'mg', 168,
 ARRAY['nausea','constipation','dry mouth','sexual dysfunction','vomiting'],
 'CYP2D6 substrate — adjust dose with strong CYP2D6 inhibitors (e.g., bupropion, fluoxetine). Avoid MAOIs.',
 'Multimodal antidepressant acting on serotonin receptors and reuptake transporter. May have cognitive benefits over standard SSRIs.',
 'Depression, generalized anxiety disorder',
 '5–20 mg/day, once daily.',
 'Lowest risk of discontinuation syndrome among serotonergic antidepressants in clinical use. Gradual taper still preferred.',
 '["5 mg","10 mg","15 mg","20 mg"]'::jsonb),

-- ── SNRIs ──────────────────────────────────────────────────────────────────
('venlafaxine', 'SNRI', 75, 'mg', 168,
 ARRAY['nausea','insomnia','sexual dysfunction','hypertension','dry mouth','sweating','discontinuation syndrome'],
 'Can raise blood pressure at higher doses — monitor BP. High discontinuation syndrome risk; taper slowly. Avoid MAOIs.',
 'SNRI that inhibits both serotonin and norepinephrine reuptake. Higher doses provide more norepinephrine effect, useful for pain and difficult depression.',
 'Depression, GAD, social anxiety disorder, panic disorder, fibromyalgia, chronic pain',
 '37.5–375 mg/day; extended-release taken once daily. Most patients respond at 75–225 mg.',
 'HIGH discontinuation risk — taper very slowly. Stopping abruptly causes severe dizziness, nausea, sweating, sensory disturbances, and irritability. Taper by 37.5 mg increments over weeks.',
 '["37.5 mg", "75 mg", "150 mg", "225 mg", "300 mg"]'::jsonb),

('duloxetine', 'SNRI', 60, 'mg', 168,
 ARRAY['nausea','dry mouth','constipation','fatigue','insomnia','sexual dysfunction','sweating'],
 'CYP2D6 substrate/inhibitor. Avoid in significant hepatic impairment. Monitor BP. Avoid MAOIs.',
 'SNRI approved for both psychiatric and pain conditions. Particularly useful when depression coexists with chronic pain.',
 'Depression, GAD, diabetic peripheral neuropathy, fibromyalgia, chronic musculoskeletal pain, stress incontinence',
 '30–120 mg/day, once daily. Start 30 mg for 1 week, then 60 mg.',
 'Taper gradually when stopping. Discontinuation symptoms include dizziness, nausea, and sensory disturbances, though generally milder than venlafaxine.',
 '["30 mg", "60 mg", "90 mg", "120 mg"]'::jsonb),

('desvenlafaxine', 'SNRI', 50, 'mg', 168,
 ARRAY['nausea','dizziness','sweating','constipation','sexual dysfunction'],
 'Active metabolite of venlafaxine. Similar interaction profile. Avoid MAOIs.',
 'Active metabolite of venlafaxine with a more predictable pharmacokinetic profile and fewer drug interactions.',
 'Depression, menopausal vasomotor symptoms (hot flashes)',
 '50 mg/day, once daily (standard dose; higher doses add side effects without added benefit for most).',
 'Taper gradually. Discontinuation syndrome risk similar to venlafaxine.',
 '["25 mg", "50 mg", "100 mg"]'::jsonb),

('levomilnacipran', 'SNRI', 40, 'mg', 168,
 ARRAY['tachycardia','hypertension','nausea','constipation','hyperhidrosis','sexual dysfunction'],
 'Norepinephrine-selective SNRI. Monitor BP and heart rate. Avoid MAOIs.',
 'Norepinephrine-preferring SNRI. May be useful when energy and motivation symptoms are prominent.',
 'Depression',
 '40–120 mg/day, once daily.',
 'Taper when stopping. Norepinephrine-mediated symptoms (elevated BP, heart rate) resolve on discontinuation.',
 '["20 mg","40 mg","80 mg","120 mg"]'::jsonb),

-- ── Atypical antidepressants ────────────────────────────────────────────────
('bupropion', 'Atypical antidepressant', 150, 'mg', 168,
 ARRAY['insomnia','dry mouth','headache','nausea','agitation','constipation','tachycardia'],
 'Lowers seizure threshold — contraindicated with seizure disorders, eating disorders, or benzodiazepine withdrawal. Strong CYP2D6 inhibitor. Stimulant-like properties. Avoid MAOIs.',
 'Dopamine and norepinephrine reuptake inhibitor with stimulant-like properties. Does not cause sexual dysfunction. Also used for smoking cessation.',
 'Depression, seasonal affective disorder, smoking cessation, ADHD (off-label)',
 '150–450 mg/day. XL form dosed once daily; SR form twice daily. Do not exceed 150 mg per dose (seizure risk).',
 'Taper when stopping. Abrupt discontinuation may worsen mood and cause irritability. Seizure risk is highest during rapid dose changes.',
 '["150 mg SR", "300 mg XL", "450 mg XL"]'::jsonb),

('mirtazapine', 'Atypical antidepressant', 15, 'mg', 168,
 ARRAY['sedation','weight gain','increased appetite','dry mouth','dizziness','constipation'],
 'H1 antihistamine mechanism — sedating, useful for insomnia and low appetite. Additive CNS depression with alcohol and benzodiazepines. Avoid MAOIs.',
 'Noradrenergic and specific serotonergic antidepressant (NaSSA). Highly sedating and appetite-stimulating — especially useful for patients with insomnia and weight loss.',
 'Depression, insomnia (off-label), appetite stimulation, nausea (off-label)',
 '7.5–45 mg/day, once daily at bedtime. Paradoxically less sedating at higher doses.',
 'Taper gradually. Stopping abruptly may cause nausea, anxiety, and rebound insomnia. Discontinuation syndrome less severe than SSRIs/SNRIs.',
 '["7.5 mg", "15 mg", "30 mg", "45 mg"]'::jsonb),

('trazodone', 'Atypical antidepressant', 50, 'mg', 48,
 ARRAY['sedation','orthostatic hypotension','dizziness','dry mouth','blurred vision','priapism'],
 'Commonly used off-label for insomnia at 50–100 mg. Risk of priapism. Additive CNS depression. Avoid MAOIs. CYP3A4 substrate.',
 'Serotonin antagonist and reuptake inhibitor (SARI). Strongly sedating; most commonly prescribed at low doses for insomnia rather than at antidepressant doses.',
 'Depression, insomnia (off-label)',
 '50–600 mg/day; 25–100 mg at bedtime for insomnia; 150–600 mg/day for depression (split doses).',
 'Low discontinuation syndrome risk at insomnia doses. Higher antidepressant doses should be tapered.',
 '["50 mg", "100 mg", "150 mg", "300 mg"]'::jsonb),

('nefazodone', 'Atypical antidepressant', 200, 'mg', 168,
 ARRAY['sedation','nausea','dry mouth','constipation','blurred vision','dizziness'],
 'Potent CYP3A4 inhibitor — multiple drug interactions. Rare but serious hepatotoxicity. Avoid MAOIs and CYP3A4 substrates with narrow therapeutic index.',
 'Serotonin antagonist and reuptake inhibitor. Less commonly prescribed due to rare hepatotoxicity risk and significant drug interactions.',
 'Depression, PTSD (off-label), insomnia',
 '300–600 mg/day in two divided doses.',
 'Taper when stopping. Abrupt discontinuation may cause nausea, dizziness, and anxiety.',
 '["100 mg","150 mg","200 mg","250 mg"]'::jsonb),

-- ── TCAs ───────────────────────────────────────────────────────────────────
('amitriptyline', 'Tricyclic antidepressant', 75, 'mg', 168,
 ARRAY['dry mouth','constipation','sedation','weight gain','orthostatic hypotension','blurred vision','urinary retention','QT prolongation'],
 'High anticholinergic burden. QT prolongation risk. Lethal in overdose. Avoid MAOIs. Multiple drug interactions — CYP2D6 substrate.',
 'One of the oldest antidepressants. Highly sedating; widely used off-label for chronic pain, migraine prevention, and insomnia at low doses.',
 'Depression, neuropathic pain (off-label), migraine prophylaxis (off-label), insomnia (off-label)',
 '10–300 mg/day; 10–50 mg at night for pain/insomnia; 75–150 mg/day for depression.',
 'Taper gradually. Anticholinergic rebound (nausea, diarrhea, agitation) may occur on abrupt discontinuation.',
 '["10 mg", "25 mg", "50 mg", "75 mg", "100 mg", "150 mg"]'::jsonb),

('nortriptyline', 'Tricyclic antidepressant', 75, 'mg', 168,
 ARRAY['dry mouth','constipation','sedation','orthostatic hypotension','blurred vision','weight gain'],
 'Less sedating than amitriptyline. QT prolongation risk. Monitor therapeutic drug levels. Avoid MAOIs. CYP2D6 substrate.',
 'Secondary amine TCA with less sedation and fewer anticholinergic effects than amitriptyline. Sometimes monitored with blood levels.',
 'Depression, neuropathic pain (off-label), smoking cessation (off-label)',
 '25–150 mg/day, once daily at night.',
 'Taper gradually when stopping to avoid anticholinergic rebound and mood destabilization.',
 '["10 mg", "25 mg", "50 mg", "75 mg"]'::jsonb),

('clomipramine', 'Tricyclic antidepressant', 50, 'mg', 336,
 ARRAY['dry mouth','constipation','sedation','weight gain','sexual dysfunction','tremor','seizures'],
 'First-line for OCD. Lowers seizure threshold more than other TCAs. Strong CYP2D6 inhibitor. Avoid MAOIs.',
 'TCA with the most potent serotonin reuptake inhibition; considered first-line for severe OCD alongside SSRIs.',
 'OCD, depression, panic disorder, chronic pain (off-label)',
 '25–250 mg/day, once daily at night or in divided doses.',
 'Taper slowly. Discontinuation causes anticholinergic rebound and mood changes.',
 '["25 mg", "50 mg", "75 mg", "100 mg"]'::jsonb),

('imipramine', 'Tricyclic antidepressant', 50, 'mg', 168,
 ARRAY['dry mouth','constipation','sedation','orthostatic hypotension','weight gain','urinary retention','QT prolongation'],
 'High anticholinergic and cardiac side-effect burden. Avoid MAOIs. CYP2D6 substrate. Lethal in overdose.',
 'One of the original antidepressants. High side-effect burden limits use; sometimes prescribed for enuresis or panic disorder.',
 'Depression, panic disorder, childhood enuresis',
 '75–300 mg/day for depression; 10–75 mg at night for enuresis.',
 'Taper gradually. Abrupt discontinuation causes significant anticholinergic rebound.',
 '["10 mg","25 mg","50 mg","75 mg"]'::jsonb),

-- ── MAOIs ──────────────────────────────────────────────────────────────────
('phenelzine', 'MAOI', 45, 'mg', 336,
 ARRAY['orthostatic hypotension','insomnia','sedation','weight gain','sexual dysfunction','edema','hypertensive crisis with tyramine'],
 'Strict tyramine-free diet required. Dangerous interactions: SSRIs, SNRIs, stimulants, most opioids, sympathomimetics, dextromethorphan. 2-week washout required before starting another antidepressant.',
 'Irreversible MAOI antidepressant. Reserved for treatment-resistant depression due to strict dietary restrictions and serious drug interaction risks.',
 'Treatment-resistant depression, social anxiety disorder, atypical depression',
 '15–90 mg/day in 2–4 divided doses.',
 'Taper gradually over 2+ weeks. Rebound depression and anxiety possible. MAOI activity persists for ~2 weeks after the last dose — maintain all dietary and drug precautions during this period.',
 '["15 mg", "30 mg", "45 mg", "60 mg"]'::jsonb),

('tranylcypromine', 'MAOI', 30, 'mg', 336,
 ARRAY['insomnia','agitation','orthostatic hypotension','hypertensive crisis with tyramine','weight loss'],
 'Same interaction and dietary restrictions as phenelzine. Has amphetamine-like stimulant activity. 2-week washout required.',
 'Irreversible MAOI with mild amphetamine-like stimulant properties. Strict dietary restrictions required.',
 'Treatment-resistant depression, atypical depression',
 '10–60 mg/day in divided doses.',
 'Taper slowly. Stimulant rebound (fatigue, depression) and rebound anxiety on stopping. MAOI activity persists 2 weeks after last dose.',
 '["10 mg", "20 mg", "30 mg"]'::jsonb),

('selegiline', 'MAOI', 6, 'mg', 336,
 ARRAY['insomnia','nausea','application-site reaction (patch form)','orthostatic hypotension'],
 'Transdermal 6 mg/day patch requires no dietary restrictions. Oral high-dose: full MAOI restrictions apply. Drug interactions same as other MAOIs.',
 'Selective MAO-B inhibitor at low doses. Transdermal patch form avoids first-pass metabolism and the tyramine food restrictions at the 6 mg dose.',
 'Depression (patch form), Parkinson disease (oral low dose)',
 'Patch: 6–12 mg/24h. Oral (Parkinson): 5 mg twice daily.',
 'Remove patch and taper. MAOI activity persists for up to 2 weeks — maintain drug interaction precautions.',
 '["6 mg patch","9 mg patch","12 mg patch"]'::jsonb),

-- ── Mood stabilizers ────────────────────────────────────────────────────────
('lithium', 'Mood stabilizer', 300, 'mg', 336,
 ARRAY['tremor','polyuria','polydipsia','weight gain','cognitive dulling','hypothyroidism','acne','nausea'],
 'Narrow therapeutic index — monitor serum levels (0.6–1.2 mEq/L), renal function, and TSH. NSAIDs, diuretics, and ACE inhibitors raise lithium levels to toxic range. Dehydration and low-sodium diet increase toxicity risk.',
 'The gold-standard mood stabilizer for bipolar disorder. Requires regular blood level monitoring. Has demonstrated antisuicidal properties.',
 'Bipolar disorder (mania and depression prevention), treatment-resistant depression (augmentation), cluster headache (off-label)',
 '900–1800 mg/day in divided doses; target serum level 0.6–1.2 mEq/L (acute mania) or 0.6–0.8 mEq/L (maintenance).',
 'Taper gradually when stopping. Abrupt discontinuation may trigger rebound mania or depression. Rebound risk is highest in the first 3 months after stopping.',
 '["150 mg", "300 mg", "450 mg", "600 mg"]'::jsonb),

('lamotrigine', 'Mood stabilizer / anticonvulsant', 100, 'mg', 336,
 ARRAY['rash (may be severe)','dizziness','headache','diplopia','ataxia','nausea','insomnia'],
 'Titrate slowly — rapid escalation causes Stevens-Johnson syndrome risk. Valproate approximately doubles lamotrigine levels (halve lamotrigine dose). Combined oral contraceptives reduce lamotrigine levels by ~50%.',
 'Anticonvulsant with mood-stabilizing properties. Particularly effective for bipolar depression. Must be started at a very low dose and titrated slowly to reduce rash risk.',
 'Bipolar disorder (especially depression), epilepsy',
 '25–400 mg/day; titrate by 25–50 mg every 1–2 weeks. Target maintenance 100–400 mg/day (lower if taking valproate).',
 'Taper over 2+ weeks when stopping. Abrupt discontinuation risks seizure recurrence. Skin rash or Stevens-Johnson syndrome risk is highest during dose escalation, not on stable doses.',
 '["25 mg", "50 mg", "100 mg", "150 mg", "200 mg"]'::jsonb),

('valproate', 'Mood stabilizer / anticonvulsant', 500, 'mg', 168,
 ARRAY['nausea','weight gain','hair loss','tremor','sedation','liver toxicity','thrombocytopenia'],
 'Monitor LFTs and CBC. Teratogenic — use effective contraception. Roughly doubles lamotrigine levels. Interacts with carbamazepine and other anticonvulsants.',
 'Broad-spectrum mood stabilizer and anticonvulsant. Effective for acute mania and seizure prevention. Requires regular blood monitoring.',
 'Bipolar disorder (acute mania and maintenance), epilepsy, migraine prophylaxis',
 '750–2000 mg/day in divided doses; target serum level 50–125 mcg/mL.',
 'Taper gradually over weeks. Abrupt discontinuation may trigger rebound seizures or mood episodes.',
 '["125 mg", "250 mg", "500 mg", "750 mg"]'::jsonb),

('carbamazepine', 'Mood stabilizer / anticonvulsant', 400, 'mg', 336,
 ARRAY['dizziness','ataxia','diplopia','nausea','leukopenia','hyponatremia','rash'],
 'Potent CYP3A4 inducer — lowers levels of most antipsychotics, antidepressants, benzodiazepines, and oral contraceptives. Monitor CBC and sodium. Stevens-Johnson risk. Avoid clozapine (additive bone marrow suppression).',
 'Mood stabilizer and anticonvulsant that strongly induces liver enzymes, reducing the effectiveness of many co-medications including hormonal contraception.',
 'Bipolar disorder, epilepsy, trigeminal neuralgia',
 '400–1200 mg/day in divided doses; target serum level 4–12 mcg/mL.',
 'Taper over weeks. Abrupt stopping may trigger rebound seizures or mood episodes.',
 '["100 mg", "200 mg", "400 mg"]'::jsonb),

('oxcarbazepine', 'Anticonvulsant / mood stabilizer', 300, 'mg', 168,
 ARRAY['dizziness','diplopia','fatigue','hyponatremia','nausea','ataxia'],
 'CYP3A4 inducer (weaker than carbamazepine). Hyponatremia risk — monitor sodium. Reduces OCP efficacy. Fewer drug interactions than carbamazepine.',
 'Structural relative of carbamazepine with fewer drug interactions and better tolerability. Induces some liver enzymes.',
 'Epilepsy, bipolar disorder (off-label), trigeminal neuralgia',
 '600–2400 mg/day in two divided doses.',
 'Taper gradually. Abrupt discontinuation may trigger seizures.',
 '["150 mg","300 mg","600 mg"]'::jsonb),

-- ── Antipsychotics ──────────────────────────────────────────────────────────
('quetiapine', 'Atypical antipsychotic', 100, 'mg', 8,
 ARRAY['sedation','weight gain','orthostatic hypotension','dry mouth','constipation','metabolic syndrome','QT prolongation'],
 'QT prolongation — avoid other QT-prolonging agents. CYP3A4 substrate. Monitor metabolic parameters (weight, glucose, lipids). Commonly used off-label for insomnia and anxiety.',
 'Broad-spectrum antipsychotic and mood stabilizer. Highly sedating at low doses; often prescribed off-label for sleep and anxiety.',
 'Schizophrenia, bipolar disorder (mania and depression), adjunct for depression, insomnia (off-label)',
 '50–800 mg/day. 25–100 mg at bedtime for insomnia; 300–800 mg/day for schizophrenia/bipolar.',
 'Taper when stopping. Abrupt discontinuation may cause rebound insomnia, nausea, and irritability. Psychosis relapse risk if stopping for primary indication.',
 '["25 mg", "50 mg", "100 mg", "200 mg", "300 mg", "400 mg"]'::jsonb),

('aripiprazole', 'Atypical antipsychotic', 10, 'mg', 168,
 ARRAY['akathisia','insomnia','nausea','headache','constipation','modest weight gain'],
 'Partial D2 agonist. Less metabolic burden than most antipsychotics. CYP2D6 and CYP3A4 substrate. Akathisia is common. Monitor for tardive dyskinesia.',
 'Partial dopamine agonist with a unique mechanism. Low metabolic side-effect burden compared to other antipsychotics. Injectable monthly form available.',
 'Schizophrenia, bipolar mania, adjunct for depression, irritability in autism, Tourette syndrome',
 '2–30 mg/day, once daily.',
 'Taper gradually when stopping. Abrupt discontinuation may trigger rebound psychosis or mood symptoms.',
 '["2 mg", "5 mg", "10 mg", "15 mg", "20 mg", "30 mg"]'::jsonb),

('risperidone', 'Atypical antipsychotic', 2, 'mg', 48,
 ARRAY['EPS / akathisia','prolactin elevation','weight gain','sedation','orthostatic hypotension','tardive dyskinesia'],
 'High prolactin elevation. CYP2D6 substrate. QT prolongation risk. Higher EPS risk than most other atypicals. Monitor metabolic parameters.',
 'Atypical antipsychotic with notable dopamine D2 blockade. Higher extrapyramidal side-effect risk than some other atypicals.',
 'Schizophrenia, bipolar mania, irritability in autism spectrum disorder',
 '1–16 mg/day (schizophrenia); 0.5–3 mg/day (agitation in elderly, off-label).',
 'Taper over weeks. Abrupt stopping risks rebound psychosis and withdrawal dyskinesia.',
 '["0.5 mg", "1 mg", "2 mg", "3 mg", "4 mg", "6 mg"]'::jsonb),

('olanzapine', 'Atypical antipsychotic', 10, 'mg', 48,
 ARRAY['weight gain','sedation','metabolic syndrome','hyperglycemia','constipation','dyslipidemia'],
 'Highest metabolic burden of atypicals — monitor weight, glucose, and lipids frequently. Additive CNS depression with other sedatives. Avoid MAOIs.',
 'Highly effective antipsychotic and mood stabilizer with the highest metabolic side-effect risk in its class. Significant weight gain common.',
 'Schizophrenia, bipolar mania and depression, treatment-resistant depression (with fluoxetine)',
 '5–20 mg/day, once daily.',
 'Taper gradually. Abrupt discontinuation risks rebound psychosis, nausea, diaphoresis, and insomnia.',
 '["2.5 mg", "5 mg", "10 mg", "15 mg", "20 mg"]'::jsonb),

('ziprasidone', 'Atypical antipsychotic', 60, 'mg', 48,
 ARRAY['QT prolongation','insomnia','nausea','dizziness','akathisia','EPS'],
 'Must be taken with ≥500 calories — absorption is highly food-dependent. QT prolongation — avoid combining with other QT-prolonging agents. Twice-daily dosing required.',
 'Antipsychotic with the lowest metabolic burden of the class. Must be taken with food for adequate absorption. QT prolongation is a notable risk.',
 'Schizophrenia, bipolar mania',
 '40–160 mg/day in two divided doses, always with food.',
 'Taper gradually. Abrupt stopping may cause withdrawal insomnia, nausea, and rebound psychosis.',
 '["20 mg", "40 mg", "60 mg", "80 mg"]'::jsonb),

('lurasidone', 'Atypical antipsychotic', 40, 'mg', 48,
 ARRAY['akathisia','nausea','sedation','EPS','insomnia','anxiety'],
 'Must be taken with ≥350 calories. Low metabolic burden. CYP3A4 substrate — avoid strong inhibitors/inducers. Once-daily dosing.',
 'Atipsychotic with favorable metabolic profile and FDA approval for bipolar depression. Requires food for absorption.',
 'Schizophrenia, bipolar depression',
 '20–160 mg/day, once daily with food.',
 'Taper when stopping. Rebound psychosis or mood episodes possible with abrupt discontinuation.',
 '["20 mg", "40 mg", "60 mg", "80 mg", "120 mg"]'::jsonb),

('clozapine', 'Atypical antipsychotic', 200, 'mg', 168,
 ARRAY['agranulocytosis','sedation','weight gain','hypersalivation','myocarditis','seizures','metabolic syndrome','constipation'],
 'Mandatory CBC monitoring (REMS program) — agranulocytosis risk. Avoid carbamazepine (additive bone marrow suppression). Fluvoxamine dramatically raises clozapine levels. QT prolongation. Constipation can be severe.',
 'Most effective antipsychotic for treatment-resistant schizophrenia. Requires weekly/biweekly blood counts due to rare but life-threatening agranulocytosis.',
 'Treatment-resistant schizophrenia, suicidality in schizophrenia',
 '12.5–900 mg/day in divided doses; titrate slowly. Target 200–450 mg/day for most patients.',
 'Taper very slowly (months). Abrupt discontinuation causes severe rebound psychosis, agitation, and cholinergic rebound (sweating, nausea). Do not stop abruptly.',
 '["25 mg", "50 mg", "100 mg", "200 mg"]'::jsonb),

('haloperidol', 'Typical antipsychotic', 5, 'mg', 24,
 ARRAY['EPS','akathisia','tardive dyskinesia','QT prolongation','neuroleptic malignant syndrome','prolactin elevation','sedation'],
 'High EPS risk. QT prolongation — avoid other QT-prolonging agents. NMS risk. CYP2D6 substrate. Use lowest effective dose.',
 'Classic first-generation antipsychotic with high dopamine D2 blockade. High extrapyramidal side-effect risk. Used primarily for acute agitation and psychosis.',
 'Schizophrenia, acute agitation, Tourette syndrome, severe nausea/vomiting (off-label)',
 '0.5–20 mg/day; acute agitation may require higher doses under supervision.',
 'Taper gradually when possible. Abrupt discontinuation risks rebound psychosis, cholinergic rebound, and withdrawal dyskinesia.',
 '["0.5 mg", "1 mg", "2 mg", "5 mg", "10 mg"]'::jsonb),

('paliperidone', 'Atypical antipsychotic', 6, 'mg', 48,
 ARRAY['EPS / akathisia','prolactin elevation','weight gain','sedation','tachycardia','QT prolongation'],
 'Active metabolite of risperidone. Renally cleared — adjust dose in renal impairment. High prolactin elevation. QT prolongation risk.',
 'Active metabolite of risperidone. Renally eliminated — useful when hepatic metabolism is a concern. Long-acting injectable form available.',
 'Schizophrenia, schizoaffective disorder',
 '3–12 mg/day, once daily.',
 'Taper when stopping. Same rebound risks as risperidone.',
 '["3 mg", "6 mg", "9 mg", "12 mg"]'::jsonb),

('brexpiprazole', 'Atypical antipsychotic', 2, 'mg', 168,
 ARRAY['akathisia','weight gain','somnolence','constipation','restlessness'],
 'FDA-approved as adjunct for MDD and for schizophrenia. CYP2D6 and CYP3A4 substrate. Similar to aripiprazole. Monitor metabolic parameters.',
 'Partial dopamine agonist related to aripiprazole. FDA-approved both as an adjunct for depression and for schizophrenia.',
 'Schizophrenia, adjunct for depression',
 '0.5–4 mg/day for depression adjunct; 2–4 mg/day for schizophrenia.',
 'Taper gradually. Abrupt stopping may cause rebound mood or psychotic symptoms.',
 '["0.5 mg", "1 mg", "2 mg", "3 mg", "4 mg"]'::jsonb),

('cariprazine', 'Atypical antipsychotic', 1.5, 'mg', 168,
 ARRAY['akathisia','EPS','weight gain','nausea','insomnia','somnolence'],
 'CYP3A4 substrate. Long-acting active metabolite (DCAR). Dose-adjust with CYP3A4 inhibitors/inducers. Approved for schizophrenia and bipolar depression.',
 'Partial dopamine agonist with long-acting active metabolite. Particularly studied for bipolar depression.',
 'Schizophrenia, bipolar depression, bipolar mania',
 '1.5–6 mg/day, once daily.',
 'Taper gradually. Active metabolite persists for weeks after stopping — full offset of effects is slow.',
 '["1.5 mg", "3 mg", "4.5 mg", "6 mg"]'::jsonb),

('asenapine', 'Atypical antipsychotic', 5, 'mg', 48,
 ARRAY['sedation','akathisia','oral hypoesthesia','weight gain','dizziness','EPS'],
 'Sublingual administration only — do not swallow or take with food/water for 10 min. CYP1A2 substrate/inhibitor. Monitor metabolic parameters.',
 'Antipsychotic and mood stabilizer administered sublingually. Direct absorption under the tongue bypasses first-pass metabolism.',
 'Schizophrenia, bipolar mania',
 '5–20 mg/day in two sublingual doses.',
 'Taper when stopping. Rebound psychosis or mania possible with abrupt discontinuation.',
 '["5 mg SL","10 mg SL"]'::jsonb),

-- ── Benzodiazepines ─────────────────────────────────────────────────────────
('alprazolam', 'Benzodiazepine', 0.5, 'mg', 1,
 ARRAY['sedation','cognitive impairment','dependence','tolerance','rebound anxiety','memory impairment','falls'],
 'High-potency, short half-life — higher abuse liability and discontinuation symptoms than long-acting benzos. Combined CNS/respiratory depression with opioids (potentially fatal). Do not abruptly discontinue after regular use.',
 'High-potency, short-acting benzodiazepine. Rapid onset useful for acute anxiety but short half-life increases dependence risk and withdrawal severity.',
 'Panic disorder, generalized anxiety disorder, acute anxiety',
 '0.25–4 mg/day in divided doses (max 10 mg/day for panic disorder). Regular use not recommended beyond 4 weeks.',
 'NEVER stop abruptly after regular use — seizure risk. Taper by 10–25% per week over weeks to months. Withdrawal includes severe anxiety, insomnia, tremor, and potentially life-threatening seizures.',
 '["0.25 mg", "0.5 mg", "1 mg", "2 mg"]'::jsonb),

('clonazepam', 'Benzodiazepine', 0.5, 'mg', 2,
 ARRAY['sedation','cognitive impairment','ataxia','dependence','tolerance','depression','memory impairment'],
 'Long half-life — less rebound anxiety. Additive CNS/respiratory depression. Dependence risk with long-term use. Taper slowly on discontinuation.',
 'Long-acting benzodiazepine with anticonvulsant properties. More stable blood levels reduce rebound anxiety between doses.',
 'Panic disorder, seizure disorders, akathisia (off-label), REM sleep behavior disorder (off-label)',
 '0.5–20 mg/day in divided doses (seizures); 0.5–4 mg/day (anxiety).',
 'Taper slowly over weeks to months. Long half-life reduces but does not eliminate withdrawal severity. Seizure risk with abrupt discontinuation.',
 '["0.25 mg", "0.5 mg", "1 mg", "2 mg"]'::jsonb),

('lorazepam', 'Benzodiazepine', 1, 'mg', 1,
 ARRAY['sedation','respiratory depression','dependence','anterograde amnesia','falls','cognitive impairment'],
 'No active metabolites — preferred in hepatic impairment and elderly (though still Beers Criteria). Additive CNS/respiratory depression with opioids and alcohol. Dependence risk.',
 'Intermediate-acting benzodiazepine with no active metabolites — simpler elimination profile than diazepam. Preferred in hospital settings.',
 'Anxiety, seizures, alcohol withdrawal, procedural sedation, insomnia',
 '0.5–10 mg/day in divided doses depending on indication.',
 'Taper slowly. Abrupt discontinuation after regular use risks seizures and severe anxiety. Long-term use requires a slow, monitored taper.',
 '["0.5 mg", "1 mg", "2 mg"]'::jsonb),

('diazepam', 'Benzodiazepine', 5, 'mg', 1,
 ARRAY['sedation','cognitive impairment','ataxia','dependence','tolerance','respiratory depression'],
 'Very long half-life (20–100 h) with active metabolites — accumulates especially in elderly. Additive CNS/respiratory depression. Dependence risk with regular use.',
 'Long-acting benzodiazepine with very long half-life and active metabolites. Used for alcohol withdrawal, muscle spasm, and anxiety.',
 'Anxiety, alcohol withdrawal, muscle spasm, seizures, procedural sedation',
 '2–40 mg/day in divided doses depending on indication.',
 'Taper slowly. Long half-life means the taper can be managed with less-frequent dose reductions. Abrupt discontinuation still risks seizures.',
 '["2 mg", "5 mg", "10 mg"]'::jsonb),

('temazepam', 'Benzodiazepine', 15, 'mg', 0.5,
 ARRAY['sedation','dizziness','cognitive impairment','dependence','next-day hangover'],
 'Short-acting — used for sleep initiation. Dependence risk. Additive CNS/respiratory depression. Avoid in elderly (Beers Criteria).',
 'Short-to-intermediate acting benzodiazepine used primarily for insomnia. Not recommended for long-term nightly use.',
 'Insomnia (short-term)',
 '7.5–30 mg at bedtime.',
 'Taper gradually after regular use. Rebound insomnia and anxiety are common on stopping.',
 '["7.5 mg", "15 mg", "22.5 mg", "30 mg"]'::jsonb),

('oxazepam', 'Benzodiazepine', 15, 'mg', 2,
 ARRAY['sedation','dizziness','cognitive impairment','ataxia','dependence'],
 'No active metabolites — safest benzo in hepatic impairment and elderly. Slow onset. Dependence and CNS depression risks apply.',
 'Short-acting benzodiazepine with no active metabolites. Safest choice in liver disease and elderly due to simple elimination.',
 'Anxiety, alcohol withdrawal, insomnia',
 '10–120 mg/day in 3–4 divided doses.',
 'Taper slowly. Dependence and withdrawal risks same as other benzodiazepines.',
 '["10 mg","15 mg","30 mg"]'::jsonb),

-- ── Stimulants ──────────────────────────────────────────────────────────────
('methylphenidate', 'Stimulant', 10, 'mg', 1,
 ARRAY['appetite suppression','insomnia','anxiety','tachycardia','hypertension','headache','irritability'],
 'Schedule II. Monitor cardiovascular status. Avoid in structural cardiac disease. Contraindicated with MAOIs. May worsen anxiety and tics.',
 'Dopamine and norepinephrine reuptake inhibitor. First-line ADHD medication available in multiple formulations (immediate, extended, patch).',
 'ADHD, narcolepsy',
 '5–60 mg/day. IR: 2–3 doses daily. ER: once daily in morning.',
 'No physiological withdrawal syndrome, but stopping may cause fatigue, increased sleep, low mood, and increased appetite for 1–2 weeks.',
 '["5 mg IR", "10 mg IR", "20 mg IR", "18 mg ER", "27 mg ER", "36 mg ER", "54 mg ER"]'::jsonb),

('amphetamine', 'Stimulant', 10, 'mg', 1,
 ARRAY['appetite suppression','insomnia','anxiety','tachycardia','hypertension','irritability','dependence'],
 'Schedule II. Absolute contraindication with MAOIs (hypertensive crisis). Monitor BP and HR. May worsen anxiety, tics, or psychosis. High abuse potential.',
 'Mixed amphetamine salts (e.g., Adderall). Releases dopamine and norepinephrine in addition to blocking reuptake.',
 'ADHD, narcolepsy',
 '5–60 mg/day. IR: 2–3 doses daily. XR: once daily in morning.',
 'Stopping after regular use may cause significant fatigue, increased sleep, low mood, and increased appetite for days to weeks.',
 '["5 mg", "10 mg", "15 mg", "20 mg", "25 mg", "30 mg"]'::jsonb),

('lisdexamfetamine', 'Stimulant', 30, 'mg', 2,
 ARRAY['appetite suppression','insomnia','anxiety','tachycardia','hypertension','dry mouth','irritability'],
 'Prodrug of d-amphetamine — activated by gut enzymes. Schedule II. Contraindicated with MAOIs. Cardiovascular monitoring required. Lower abuse potential than immediate-release amphetamines.',
 'Prodrug converted to active dextroamphetamine in the body. Extended, smooth duration of action. Also approved for binge eating disorder.',
 'ADHD, binge eating disorder',
 '20–70 mg/day, once daily in morning.',
 'Stopping may cause fatigue, increased sleep, and low mood for days to weeks. Less pronounced than IR amphetamines due to gradual conversion.',
 '["20 mg", "30 mg", "40 mg", "50 mg", "60 mg", "70 mg"]'::jsonb),

('dextroamphetamine', 'Stimulant', 10, 'mg', 1,
 ARRAY['appetite suppression','insomnia','anxiety','tachycardia','hypertension','dry mouth','dependence'],
 'Schedule II. Same interaction profile as amphetamine. Contraindicated with MAOIs. High abuse potential.',
 'Pure dextrorotary amphetamine isomer. More potent CNS stimulant than mixed amphetamine salts.',
 'ADHD, narcolepsy',
 '5–60 mg/day in divided doses (IR) or once daily (ER).',
 'Stopping after regular use may cause significant fatigue, increased sleep, and low mood for days to weeks.',
 '["5 mg", "10 mg", "15 mg"]'::jsonb),

('dexmethylphenidate', 'Stimulant', 5, 'mg', 1,
 ARRAY['appetite suppression','insomnia','anxiety','tachycardia','headache','abdominal pain'],
 'D-enantiomer of methylphenidate. Schedule II. Same warnings and contraindications as methylphenidate.',
 'Active d-enantiomer of methylphenidate. Allows lower mg dosing than racemic methylphenidate.',
 'ADHD',
 '5–20 mg/day. IR: twice daily. ER (Focalin XR): once daily.',
 'Same as methylphenidate — fatigue and low mood for 1–2 weeks after stopping.',
 '["5 mg IR", "10 mg IR", "5 mg ER", "10 mg ER", "20 mg ER", "30 mg ER", "40 mg ER"]'::jsonb),

('atomoxetine', 'Non-stimulant ADHD', 40, 'mg', 336,
 ARRAY['decreased appetite','nausea','dry mouth','insomnia','irritability','urinary hesitancy','mood lability'],
 'Not a controlled substance. CYP2D6 substrate — fluoxetine, paroxetine, bupropion significantly raise levels; reduce dose. Monitor BP and HR.',
 'Selective norepinephrine reuptake inhibitor. Non-stimulant; no abuse potential. Full effect takes 4–8 weeks.',
 'ADHD',
 '40–100 mg/day (up to 1.4 mg/kg/day); once daily or split morning/afternoon.',
 'Taper when stopping. Stopping may cause mild rebound ADHD symptoms. No significant physiological withdrawal syndrome.',
 '["10 mg", "18 mg", "25 mg", "40 mg", "60 mg", "80 mg", "100 mg"]'::jsonb),

('viloxazine', 'Non-stimulant ADHD', 100, 'mg', 24,
 ARRAY['somnolence','decreased appetite','nausea','irritability','headache'],
 'CYP1A2 inhibitor — raises levels of caffeine, clozapine, and other CYP1A2 substrates. CYP3A4 inducer. Monitor for serotonergic effects.',
 'Norepinephrine reuptake inhibitor with serotonergic activity. Newer non-stimulant ADHD option.',
 'ADHD (pediatric and adult)',
 '100–600 mg/day, once daily.',
 'No significant physiological withdrawal. Stopping may cause mild rebound inattention.',
 '["100 mg", "150 mg", "200 mg"]'::jsonb),

('guanfacine', 'Alpha-2 agonist / non-stimulant ADHD', 1, 'mg', 168,
 ARRAY['sedation','dry mouth','hypotension','bradycardia','constipation','irritability on discontinuation'],
 'Extended-release form used for ADHD. CYP3A4 substrate — adjust dose with inhibitors/inducers. Taper slowly on discontinuation. Additive hypotension with antihypertensives.',
 'Selective alpha-2 receptor agonist. Reduces norepinephrine signaling to improve attention and impulse control without stimulant effects.',
 'ADHD (as monotherapy or adjunct), Tourette syndrome, hypertension',
 '1–4 mg/day (ADHD ER formulation), once daily.',
 'Taper slowly — rebound hypertension and irritability on abrupt discontinuation. Lower rebound risk than clonidine.',
 '["1 mg", "2 mg", "3 mg", "4 mg"]'::jsonb),

('clonidine', 'Alpha-2 agonist', 0.1, 'mg', 2,
 ARRAY['sedation','dry mouth','hypotension','bradycardia','rebound hypertension on discontinuation','constipation'],
 'Rebound hypertension if abruptly discontinued — always taper. Additive hypotension. Used off-label for ADHD, anxiety, PTSD, and opioid/alcohol withdrawal. More sedating than guanfacine.',
 'Alpha-2 receptor agonist primarily used for blood pressure. Multiple off-label psychiatric uses including ADHD, PTSD nightmares, and withdrawal management.',
 'Hypertension, ADHD (off-label), PTSD nightmares (off-label), opioid/alcohol withdrawal symptoms (off-label)',
 '0.1–0.8 mg/day for hypertension; 0.05–0.3 mg/day for ADHD or PTSD.',
 'MUST be tapered — abrupt discontinuation causes severe rebound hypertension, anxiety, and agitation. Taper over 1–2 weeks.',
 '["0.1 mg", "0.2 mg", "0.3 mg"]'::jsonb),

('modafinil', 'Wakefulness agent', 200, 'mg', 2,
 ARRAY['headache','nausea','anxiety','insomnia','dry mouth','decreased appetite'],
 'CYP3A4 inducer — reduces efficacy of oral contraceptives and other CYP3A4 substrates. Lower abuse potential than amphetamines. Not indicated for primary insomnia.',
 'Wakefulness-promoting agent with unknown exact mechanism. Lower abuse potential than amphetamines. Also used off-label for cognitive fatigue.',
 'Narcolepsy, shift work sleep disorder, obstructive sleep apnea (adjunct), fatigue in MS and other conditions (off-label)',
 '100–400 mg/day, once daily in morning (or split for shift work).',
 'No significant physiological withdrawal. Stopping may cause rebound sleepiness for several days.',
 '["100 mg", "200 mg"]'::jsonb),

('armodafinil', 'Wakefulness agent', 150, 'mg', 2,
 ARRAY['headache','nausea','dry mouth','insomnia','anxiety','dizziness'],
 'R-enantiomer of modafinil with longer duration. Same CYP3A4 induction and interaction profile. Reduces OCP efficacy.',
 'Active R-enantiomer of modafinil. Longer duration of wakefulness-promoting effect than racemic modafinil.',
 'Narcolepsy, shift work sleep disorder, obstructive sleep apnea (adjunct)',
 '50–250 mg/day, once daily in morning.',
 'No significant physiological withdrawal. Rebound sleepiness for a few days on stopping.',
 '["50 mg","150 mg","250 mg"]'::jsonb),

-- ── Sedative-hypnotics ──────────────────────────────────────────────────────
('zolpidem', 'Sedative-hypnotic', 5, 'mg', 0.5,
 ARRAY['sedation','amnesia','sleepwalking','rebound insomnia','falls','complex sleep behaviors'],
 'Take immediately before bed with no subsequent obligations. Avoid in elderly — falls and delirium risk (Beers Criteria). Additive CNS depression with alcohol and other sedatives. Tolerance and dependence risk with nightly use.',
 'Non-benzodiazepine GABA-A receptor agonist. Rapidly induces sleep. Associated with complex sleep behaviors (sleepwalking, sleep eating) in some users.',
 'Insomnia (short-term)',
 '5–10 mg immediately before bed (5 mg in women and elderly).',
 'Rebound insomnia is common in the first 1–2 nights after stopping. Taper if used nightly for more than 2 weeks.',
 '["5 mg", "10 mg", "6.25 mg CR", "12.5 mg CR"]'::jsonb),

('eszopiclone', 'Sedative-hypnotic', 2, 'mg', 0.5,
 ARRAY['unpleasant metallic or bitter taste','sedation','dizziness','dry mouth','complex sleep behaviors'],
 'CYP3A4 substrate. Unpleasant taste in many users. Additive CNS depression with alcohol. Tolerance risk with nightly use.',
 'Non-benzodiazepine sleep aid with slightly longer duration than zolpidem. Metallic taste is a common and bothersome side effect.',
 'Insomnia',
 '1–3 mg immediately before bed (1–2 mg in elderly).',
 'Rebound insomnia on stopping. Taper if used regularly for more than 2 weeks.',
 '["1 mg", "2 mg", "3 mg"]'::jsonb),

('zaleplon', 'Sedative-hypnotic', 10, 'mg', 0.25,
 ARRAY['dizziness','amnesia','sedation','rebound insomnia','headache'],
 'Very short duration (~1 hour) — can be taken as late as 4 h before scheduled wake time. Additive CNS depression. Lower tolerance risk than longer-acting agents.',
 'Very short-acting non-benzodiazepine sleep aid. Can be used for middle-of-the-night awakenings if at least 4 hours remain before waking.',
 'Insomnia (difficulty falling asleep)',
 '5–20 mg immediately before bed.',
 'Minimal rebound insomnia due to very short duration. Low physical dependence risk compared to longer-acting sleep agents.',
 '["5 mg", "10 mg", "20 mg"]'::jsonb),

('hydroxyzine', 'Antihistamine / anxiolytic', 25, 'mg', 1,
 ARRAY['sedation','dry mouth','blurred vision','constipation','urinary retention'],
 'Non-habit-forming. Additive CNS depression with other sedatives. Anticholinergic side effects. QT prolongation at higher doses. Avoid in elderly (Beers Criteria — anticholinergic).',
 'Antihistamine with anxiolytic and sedating properties. Non-addictive and non-tolerance-forming. Useful for acute anxiety or as-needed sleep aid.',
 'Anxiety (acute), insomnia, itching/urticaria',
 '25–100 mg up to 4 times daily for anxiety; 50–100 mg at bedtime for sleep.',
 'No physiological withdrawal syndrome. Sedative effects resolve within days of stopping.',
 '["10 mg", "25 mg", "50 mg", "100 mg"]'::jsonb),

('melatonin', 'Sleep supplement', 0.5, 'mg', 0.5,
 ARRAY['daytime sleepiness','dizziness','headache','nausea'],
 'Low interaction potential. Fluvoxamine markedly increases melatonin levels (CYP1A2). May potentiate CNS depressants. Use lowest effective dose (0.5–3 mg).',
 'Hormone that regulates the sleep-wake cycle. Most people use far more than needed — the effective dose is typically 0.5–3 mg, not 10 mg.',
 'Insomnia, jet lag, circadian rhythm disorders, sleep onset (low doses)',
 '0.5–5 mg taken 30–60 minutes before bedtime. Higher doses are not more effective.',
 'No physiological withdrawal. May take a few nights to re-establish natural melatonin rhythm on stopping.',
 '["0.5 mg","1 mg","2.5 mg","3 mg","5 mg"]'::jsonb),

-- ── Anxiolytics ─────────────────────────────────────────────────────────────
('buspirone', 'Anxiolytic', 10, 'mg', 336,
 ARRAY['nausea','dizziness','headache','nervousness','insomnia','lightheadedness'],
 'Non-benzodiazepine — no addiction or abuse potential. Takes 2–4 weeks for anxiolytic effect. CYP3A4 substrate — avoid grapefruit. Avoid MAOIs. Does not treat acute anxiety.',
 'Non-addictive anxiolytic that works on serotonin receptors. Has no effect on acute anxiety — it requires weeks to build up a therapeutic effect.',
 'Generalized anxiety disorder',
 '15–60 mg/day in two to three divided doses.',
 'No physiological withdrawal syndrome. Can be stopped abruptly if needed, though anxiety symptoms may return.',
 '["5 mg","10 mg","15 mg","30 mg"]'::jsonb),

-- ── Beta-blockers ───────────────────────────────────────────────────────────
('propranolol', 'Beta-blocker', 10, 'mg', 1,
 ARRAY['bradycardia','hypotension','fatigue','bronchospasm','cold extremities','depression','sexual dysfunction'],
 'Contraindicated in asthma and COPD. Masks hypoglycemia symptoms in insulin-dependent diabetes. Additive hypotension. CYP2D6 substrate. Do not abruptly discontinue. Used off-label for performance anxiety and tremor.',
 'Non-selective beta-blocker. Used in psychiatry for performance anxiety, tremor from lithium or medications, and akathisia.',
 'Hypertension, angina, performance anxiety (off-label), tremor (off-label), akathisia (off-label), migraine prophylaxis',
 '10–320 mg/day depending on indication; 10–40 mg as-needed for performance anxiety.',
 'Taper when stopping after regular use — abrupt discontinuation may cause rebound angina or tachycardia, especially in cardiac patients.',
 '["10 mg","20 mg","40 mg","80 mg","120 mg"]'::jsonb),

-- ── Anticonvulsants used in psychiatry ─────────────────────────────────────
('gabapentin', 'Anticonvulsant / adjunctive anxiolytic', 300, 'mg', 2,
 ARRAY['sedation','dizziness','ataxia','weight gain','peripheral edema','cognitive blunting','fatigue'],
 'Increasing misuse reports — assess abuse history. Additive CNS depression with opioids, benzodiazepines, and alcohol. Respiratory depression risk when combined with opioids in patients with respiratory compromise.',
 'Anticonvulsant also used off-label for anxiety, neuropathic pain, and sleep. Binding profile different from benzodiazepines but similar sedation and misuse potential.',
 'Epilepsy, neuropathic pain, postherpetic neuralgia, restless legs syndrome, anxiety (off-label)',
 '300–3600 mg/day in three divided doses.',
 'Taper gradually over 1–2 weeks. Abrupt discontinuation may cause seizures (in epilepsy) and anxiety, insomnia, and flu-like symptoms in those using for other reasons.',
 '["100 mg", "300 mg", "400 mg", "600 mg", "800 mg"]'::jsonb),

('pregabalin', 'Anticonvulsant / anxiolytic', 75, 'mg', 2,
 ARRAY['sedation','dizziness','weight gain','peripheral edema','blurred vision','euphoria at higher doses'],
 'Schedule V — misuse potential. Additive CNS/respiratory depression with benzodiazepines and opioids. FDA-approved for generalized anxiety disorder in Europe; off-label in US.',
 'Anticonvulsant approved for anxiety in Europe. More predictable absorption than gabapentin. Schedule V due to misuse potential.',
 'Epilepsy, neuropathic pain, fibromyalgia, GAD (European approval), postherpetic neuralgia',
 '150–600 mg/day in two to three divided doses.',
 'Taper over at least 1 week. Abrupt discontinuation may cause seizures, insomnia, nausea, and anxiety.',
 '["25 mg", "50 mg", "75 mg", "100 mg", "150 mg", "200 mg", "225 mg", "300 mg"]'::jsonb),

('topiramate', 'Anticonvulsant', 25, 'mg', 168,
 ARRAY['cognitive slowing','word-finding difficulty','appetite suppression','weight loss','kidney stones','paresthesias','metabolic acidosis'],
 'CYP3A4 inducer — reduces OCP efficacy. Monitor bicarbonate levels. Used off-label for weight loss, alcohol use disorder, PTSD, and migraine prophylaxis.',
 'Anticonvulsant with weight loss and cognitive side effects. Used off-label for several psychiatric and addiction-related conditions.',
 'Epilepsy, migraine prophylaxis, weight loss (off-label), alcohol use disorder (off-label), PTSD (off-label)',
 '25–400 mg/day in two divided doses; titrate slowly (25 mg/week).',
 'Taper over 2–3 weeks. Abrupt discontinuation may trigger seizures. Weight may rebound on stopping.',
 '["25 mg","50 mg","100 mg","200 mg"]'::jsonb),

-- ── Opioid antagonists ──────────────────────────────────────────────────────
('naltrexone', 'Opioid antagonist', 50, 'mg', 2,
 ARRAY['nausea','abdominal pain','headache','insomnia','anxiety','fatigue'],
 'Contraindicated if currently using opioids — precipitates acute withdrawal. Blocks opioid analgesia. Used for AUD and OUD. Monthly injectable (Vivitrol) available. Monitor LFTs at high doses.',
 'Opioid receptor blocker used to reduce cravings in alcohol and opioid use disorders. Must be fully detoxified from opioids before starting.',
 'Alcohol use disorder, opioid use disorder (maintenance), self-injurious behavior (off-label)',
 '50 mg/day oral; 380 mg monthly injection (Vivitrol).',
 'Can be stopped without physiological withdrawal. Opioid sensitivity is restored after stopping — overdose risk increases if opioids are used after a period of naltrexone.',
 '["25 mg", "50 mg", "100 mg"]'::jsonb),

('naloxone', 'Opioid antagonist', 4, 'mg', 0.1,
 ARRAY['acute opioid withdrawal symptoms (if opioid-dependent)','nausea','tachycardia','sweating'],
 'Rescue medication for opioid overdose. Extremely short-acting — repeat dosing often needed. Has no effect in absence of opioids.',
 'Emergency opioid overdose reversal agent. Displaces opioids from receptors. Available as nasal spray (Narcan) without prescription in most states.',
 'Opioid overdose reversal',
 'Nasal: 4 mg per nostril; may repeat in 2–3 min. IM/IV: 0.4–2 mg; may repeat.',
 'Short-acting — effects wear off in 30–90 minutes. Withdrawal symptoms in opioid-dependent persons resolve as naloxone clears.',
 '["2 mg nasal","4 mg nasal","0.4 mg/mL injectable"]'::jsonb),

-- ── Other anticonvulsants ────────────────────────────────────────────────────
('levetiracetam', 'Anticonvulsant', 500, 'mg', 24,
 ARRAY['irritability','aggression','depression','fatigue','dizziness','somnolence'],
 'Renal excretion — adjust dose in renal impairment. Psychiatric side effects (irritability, mood changes) can be significant. Few pharmacokinetic interactions.',
 'Anticonvulsant with a unique mechanism and few drug interactions. Notable for causing behavioral/mood side effects in some patients.',
 'Epilepsy',
 '1000–3000 mg/day in two divided doses.',
 'Taper when stopping in epilepsy to avoid seizure recurrence. Mood/behavioral side effects resolve on stopping.',
 '["250 mg","500 mg","750 mg","1000 mg"]'::jsonb),

-- ── Adjunctive / other psychiatric ──────────────────────────────────────────
('lithium orotate', 'Dietary supplement', 5, 'mg', 168,
 ARRAY['nausea at high doses','fatigue','potential tremor at very high doses'],
 'OTC supplement — much lower doses than prescription lithium carbonate. Limited clinical evidence at supplement doses. Avoid combining with prescription lithium.',
 'Low-dose OTC lithium supplement. Different salt form from prescription lithium carbonate. Clinical evidence is limited at these doses.',
 'Mood support (supplement, limited evidence)',
 '5–20 mg/day (supplement doses — vastly lower than prescription lithium).',
 'No physiological withdrawal at supplement doses. Can be stopped without tapering.',
 '["5 mg"]'::jsonb),

('N-acetylcysteine', 'Antioxidant supplement', 600, 'mg', 24,
 ARRAY['nausea','vomiting','diarrhea','GI upset'],
 'Used adjunctively for OCD, trichotillomania, addiction, and bipolar disorder. Low interaction profile. Avoid with nitroglycerin (profound hypotension).',
 'Antioxidant supplement with glutamate-modulating properties. Used as an adjunct in several psychiatric and addiction-related conditions.',
 'OCD (adjunct, off-label), trichotillomania (off-label), addiction (off-label), bipolar disorder (adjunct, off-label)',
 '600–2400 mg/day in divided doses.',
 'No physiological withdrawal. Can be stopped without tapering.',
 '["600 mg", "1200 mg"]'::jsonb),

('esketamine', 'NMDA antagonist / antidepressant', 56, 'mg', 2,
 ARRAY['dissociation','dizziness','nausea','somnolence','increased blood pressure','vertigo'],
 'Intranasal administration in certified healthcare settings only (REMS). Rapid-acting for treatment-resistant depression. Monitor BP after each dose. Do not drive same day as dose.',
 'Intranasal ketamine enantiomer. First rapid-acting antidepressant. Administered in healthcare settings due to dissociative effects and BP monitoring requirements.',
 'Treatment-resistant depression, major depressive disorder with acute suicidality',
 '56–84 mg intranasally, twice weekly for 4 weeks, then weekly/biweekly.',
 'No standard discontinuation protocol established. Discuss maintenance schedule with prescriber. Abrupt stopping not associated with physical withdrawal.',
 '["56 mg intranasal","84 mg intranasal"]'::jsonb),

-- ── NEW: Cardiovascular / Blood Pressure ────────────────────────────────────
('lisinopril', 'ACE inhibitor', 10, 'mg', 4,
 ARRAY['dry cough','elevated potassium','dizziness','headache','kidney impairment','angioedema (rare but serious)'],
 'Serious interaction with lithium — raises lithium levels to potentially toxic range. Monitor renal function regularly. Angioedema rare but life-threatening. Avoid in pregnancy.',
 'ACE inhibitor that relaxes blood vessels by blocking angiotensin-converting enzyme. Among the most widely prescribed medications for blood pressure and heart failure.',
 'Hypertension, heart failure, diabetic nephropathy, post-MI heart protection',
 '5–40 mg/day, once daily.',
 'Can be stopped without tapering. Blood pressure may rise after stopping. No physiological withdrawal syndrome.',
 '["5 mg", "10 mg", "20 mg", "40 mg"]'::jsonb),

('losartan', 'ARB', 50, 'mg', 4,
 ARRAY['dizziness','elevated potassium','kidney impairment','headache','back pain'],
 'Serious interaction with lithium — raises lithium levels similarly to ACE inhibitors. Raises potassium. Monitor renal function. Avoid in pregnancy.',
 'Angiotensin receptor blocker (ARB). Alternative to ACE inhibitors without the cough side effect. Similar lithium interaction risk as ACE inhibitors.',
 'Hypertension, diabetic nephropathy, heart failure, stroke prevention',
 '25–100 mg/day, once daily or split twice daily.',
 'Can be stopped without tapering. Blood pressure may rise after stopping. No withdrawal syndrome.',
 '["25 mg", "50 mg", "100 mg"]'::jsonb),

('amlodipine', 'Calcium channel blocker', 5, 'mg', 24,
 ARRAY['ankle edema','flushing','headache','dizziness','palpitations','fatigue'],
 'CYP3A4 substrate. May interact with CYP3A4 inhibitors (e.g., verapamil, diltiazem, some antifungals). Grapefruit juice increases levels. Peripheral edema is common.',
 'Long-acting dihydropyridine calcium channel blocker. Primarily relaxes peripheral blood vessels. Ankle swelling is the most common complaint.',
 'Hypertension, angina, coronary artery disease',
 '2.5–10 mg/day, once daily.',
 'Can be stopped without tapering for most patients. Blood pressure may rise. No physiological withdrawal.',
 '["2.5 mg", "5 mg", "10 mg"]'::jsonb),

('metoprolol', 'Beta-blocker', 50, 'mg', 2,
 ARRAY['fatigue','bradycardia','hypotension','dizziness','depression','cold extremities','bronchospasm'],
 'Cardioselective beta-blocker — less bronchospasm than propranolol but still caution in asthma. Masks hypoglycemia. Additive bradycardia with other agents. Do not abruptly discontinue.',
 'Cardioselective beta-blocker used primarily for heart conditions. More commonly used than propranolol for cardiovascular indications. Extended-release form (succinate) is once-daily.',
 'Hypertension, angina, heart failure, atrial fibrillation, post-MI protection, migraine prophylaxis',
 '25–400 mg/day; tartrate (IR) twice daily, succinate (ER) once daily.',
 'MUST be tapered — abrupt discontinuation in cardiac patients may trigger rebound angina, hypertension, or arrhythmias. Taper over 1–2 weeks.',
 '["25 mg", "50 mg", "100 mg", "200 mg"]'::jsonb),

('atenolol', 'Beta-blocker', 50, 'mg', 2,
 ARRAY['fatigue','bradycardia','hypotension','cold extremities','depression','dizziness'],
 'Renally excreted — dose-reduce in renal impairment. Less lipophilic than propranolol — fewer CNS side effects. Do not abruptly discontinue. Caution in asthma.',
 'Cardioselective beta-blocker that does not enter the brain as readily as propranolol. Renally eliminated.',
 'Hypertension, angina, atrial fibrillation',
 '25–100 mg/day, once daily.',
 'Taper when stopping in cardiac patients. Abrupt discontinuation risks rebound hypertension and angina.',
 '["25 mg", "50 mg", "100 mg"]'::jsonb),

('hydrochlorothiazide', 'Thiazide diuretic', 25, 'mg', 4,
 ARRAY['hypokalemia','hyponatremia','hyperuricemia','increased blood glucose','dizziness','dehydration','muscle cramps'],
 'Serious interaction with lithium — sodium depletion increases lithium reabsorption causing toxicity. Raises blood sugar and uric acid. Monitor electrolytes regularly.',
 'Thiazide diuretic that reduces fluid retention by promoting sodium and water excretion by the kidneys. Among the most common blood pressure medications.',
 'Hypertension, edema from heart failure, nephrolithiasis (calcium-containing stones)',
 '12.5–50 mg/day, once daily in morning.',
 'Can be stopped without tapering. Blood pressure may rise. May notice increased urination resolves after stopping.',
 '["12.5 mg", "25 mg", "50 mg"]'::jsonb),

('furosemide', 'Loop diuretic', 40, 'mg', 1,
 ARRAY['hypokalemia','hyponatremia','dehydration','hypotension','ototoxicity (high IV doses)','increased urination','muscle cramps'],
 'Serious interaction with lithium — increases lithium reabsorption causing toxicity. More potent than thiazides. Monitor electrolytes. Ototoxicity risk at high IV doses.',
 'Powerful loop diuretic used for significant fluid retention. More potent and faster-acting than thiazides.',
 'Edema from heart failure, kidney disease, liver disease, hypertension',
 '20–600 mg/day in one to two doses depending on indication.',
 'Can generally be stopped without tapering. Fluid may accumulate again after stopping in heart failure patients.',
 '["20 mg", "40 mg", "80 mg"]'::jsonb),

('verapamil', 'Calcium channel blocker', 120, 'mg', 2,
 ARRAY['constipation','bradycardia','hypotension','dizziness','headache','ankle edema','fatigue','heart block'],
 'Potent CYP3A4 inhibitor — significantly raises levels of carbamazepine, simvastatin, cyclosporine, colchicine, and other substrates. Also slows heart rate. Constipation is very common.',
 'Non-dihydropyridine calcium channel blocker that slows the heart rate AND dilates blood vessels. Potent inhibitor of liver enzymes — significant drug interaction risk.',
 'Hypertension, angina, atrial fibrillation, migraine prophylaxis, cluster headache (off-label)',
 '120–480 mg/day; IR in 3 divided doses or SR once to twice daily.',
 'Taper when stopping for cardiac indications. Abrupt discontinuation may worsen angina. No standard withdrawal syndrome for non-cardiac indications.',
 '["40 mg IR", "80 mg IR", "120 mg IR", "120 mg SR", "180 mg SR", "240 mg SR"]'::jsonb),

('diltiazem', 'Calcium channel blocker', 120, 'mg', 2,
 ARRAY['bradycardia','hypotension','dizziness','headache','ankle edema','constipation','peripheral edema'],
 'CYP3A4 inhibitor (moderate) — raises levels of carbamazepine, simvastatin, and other CYP3A4 substrates. Slows heart rate similarly to verapamil. Multiple once-daily ER formulations available.',
 'Non-dihydropyridine calcium channel blocker that slows heart rate and dilates blood vessels. Moderate CYP3A4 inhibitor with significant drug interactions.',
 'Hypertension, angina, atrial fibrillation, rate control in atrial flutter',
 '120–540 mg/day; IR three to four times daily or ER once daily.',
 'Taper for cardiac indications. Abrupt stopping may worsen angina or heart rate control.',
 '["60 mg IR", "90 mg IR", "120 mg IR", "120 mg ER", "180 mg ER", "240 mg ER", "300 mg ER"]'::jsonb),

('simvastatin', 'Statin', 20, 'mg', 12,
 ARRAY['muscle pain / myopathy','rhabdomyolysis (rare)','liver enzyme elevation','headache','GI upset','memory concerns (rare)'],
 'CYP3A4 substrate — dose must be reduced or avoided with strong CYP3A4 inhibitors (verapamil, diltiazem, amiodarone, certain antifungals). Max 10 mg with amlodipine. Myopathy risk increases with higher doses.',
 'Cholesterol-lowering statin that inhibits HMG-CoA reductase. The most interaction-prone statin due to CYP3A4 metabolism.',
 'High LDL cholesterol, cardiovascular disease prevention, familial hypercholesterolemia',
 '5–40 mg/day, once daily at night. Dose limited by co-medications.',
 'Can be stopped without tapering. LDL cholesterol will rise after stopping. No physiological withdrawal.',
 '["5 mg","10 mg","20 mg","40 mg"]'::jsonb),

-- ── NEW: OTC Pain / Sleep / Muscle ──────────────────────────────────────────
('ibuprofen', 'NSAID', 400, 'mg', 1,
 ARRAY['GI irritation / ulcers','kidney impairment','elevated blood pressure','increased bleeding risk','fluid retention','headache'],
 'Serious interaction with lithium — NSAIDs reduce lithium clearance, raising plasma levels to toxic range. Also increases bleeding risk with SSRIs and anticoagulants. Avoid in kidney disease and heart failure.',
 'Non-steroidal anti-inflammatory drug (NSAID). One of the most commonly used OTC analgesics and anti-inflammatory medications.',
 'Pain, fever, inflammation, arthritis, menstrual cramps',
 '200–800 mg per dose; 400–2400 mg/day in 3–4 divided doses. Take with food.',
 'No physiological withdrawal. GI irritation and blood pressure effects resolve after stopping.',
 '["200 mg", "400 mg", "600 mg", "800 mg"]'::jsonb),

('naproxen', 'NSAID', 250, 'mg', 2,
 ARRAY['GI irritation','kidney impairment','elevated blood pressure','increased bleeding risk','fluid retention','headache'],
 'Same lithium interaction as ibuprofen — raises lithium to toxic range. Longer half-life than ibuprofen (can be dosed twice daily). Same bleeding and kidney risks as other NSAIDs.',
 'NSAID with a longer duration of action than ibuprofen. Available OTC (Aleve) and prescription strength.',
 'Pain, inflammation, arthritis, fever, menstrual cramps, gout',
 '220–550 mg twice daily OTC; up to 1500 mg/day prescription.',
 'No physiological withdrawal. GI and cardiovascular effects resolve after stopping.',
 '["220 mg OTC", "250 mg", "375 mg", "500 mg"]'::jsonb),

('acetaminophen', 'Analgesic / antipyretic', 500, 'mg', 1,
 ARRAY['liver toxicity in overdose or with alcohol','rash (rare)'],
 'Extremely safe at recommended doses but hepatotoxic in overdose or with heavy alcohol use. Max 3000 mg/day in regular alcohol users; 4000 mg/day otherwise. Caution with other acetaminophen-containing products.',
 'Analgesic and fever reducer. Does not have anti-inflammatory properties. Safe for stomach — does not cause GI irritation like NSAIDs.',
 'Pain, fever',
 '325–1000 mg every 4–6 hours as needed; max 4000 mg/day (3000 mg/day with alcohol use).',
 'No physiological withdrawal. Effects wear off as drug clears.',
 '["325 mg", "500 mg", "650 mg", "1000 mg"]'::jsonb),

('aspirin', 'NSAID / antiplatelet', 81, 'mg', 2,
 ARRAY['GI bleeding','tinnitus (high doses)','increased bleeding risk','Reye syndrome in children','kidney impairment'],
 'Interacts with lithium (raises levels), SSRIs (increased bleeding risk), and anticoagulants (major bleeding risk). Low-dose aspirin irreversibly inhibits platelets for their entire lifespan (~10 days).',
 'NSAID with irreversible antiplatelet properties. At low doses (81 mg), used primarily for cardiovascular protection. At higher doses, used as an anti-inflammatory.',
 'Cardiovascular event prevention, pain, fever, inflammation, stroke prevention',
 '81 mg/day for cardiovascular protection; 325–650 mg every 4–6 hours for pain/fever.',
 'No withdrawal from stopping. Platelet function recovers over ~10 days after stopping low-dose aspirin.',
 '["81 mg", "325 mg", "500 mg", "650 mg"]'::jsonb),

('diphenhydramine', 'Antihistamine / sleep aid', 25, 'mg', 0.5,
 ARRAY['sedation','dry mouth','urinary retention','constipation','blurred vision','cognitive impairment','next-day grogginess','paradoxical excitation in elderly'],
 'Strong anticholinergic — avoid in elderly, BPH, glaucoma. Additive CNS depression with benzodiazepines, opioids, and other sedatives. Rapid tolerance development means it loses sleep-promoting effects within days.',
 'First-generation antihistamine with sedating properties. Common OTC sleep aid ingredient (Benadryl, ZzzQuil, Unisom SleepTabs). Tolerance develops very rapidly.',
 'Allergies, insomnia (OTC sleep aid), motion sickness, itching',
 '25–50 mg at bedtime for sleep; 25–50 mg every 4–6 hours for allergies.',
 'No physiological withdrawal. Tolerance to sedative effects develops within a few days, so stopping simply removes the (now-minimal) benefit.',
 '["12.5 mg", "25 mg", "50 mg"]'::jsonb),

('dextromethorphan', 'Cough suppressant', 15, 'mg', 2,
 ARRAY['dizziness','sedation','nausea','serotonin effects at high doses','dissociation at very high doses'],
 'Serotonin syndrome risk with MAOIs (absolutely contraindicated) and SSRIs/SNRIs at higher doses. CYP2D6 substrate — fluoxetine and paroxetine significantly raise levels. Do not combine with MAOIs under any circumstances.',
 'OTC cough suppressant that acts on opioid and NMDA receptors. Found in many combination cold/flu products. MAOI interaction is life-threatening.',
 'Cough suppression, neuropathic pain (combined with quinidine as Nuedexta)',
 '10–30 mg every 4–6 hours as needed for cough.',
 'No physiological withdrawal at OTC cough doses.',
 '["10 mg", "15 mg", "20 mg", "30 mg"]'::jsonb),

('cyclobenzaprine', 'Muscle relaxant', 5, 'mg', 2,
 ARRAY['sedation','dry mouth','dizziness','constipation','blurred vision','tachycardia','urinary retention'],
 'Structurally related to TCAs — shares similar anticholinergic and serotonergic properties. Moderate serotonin syndrome risk with SSRIs/SNRIs. Serious risk with MAOIs (hyperpyrexia, seizures). Additive CNS depression.',
 'Centrally-acting muscle relaxant structurally similar to tricyclic antidepressants. Significant anticholinergic and serotonergic activity — more drug interactions than other muscle relaxants.',
 'Muscle spasm (short-term), fibromyalgia (off-label)',
 '5–10 mg three times daily or 15–30 mg ER once daily. Not recommended beyond 2–3 weeks.',
 'No significant physiological withdrawal at standard doses and short-term use. Muscle spasms may return after stopping.',
 '["5 mg", "7.5 mg", "10 mg", "15 mg ER", "30 mg ER"]'::jsonb),

('methocarbamol', 'Muscle relaxant', 750, 'mg', 2,
 ARRAY['sedation','dizziness','nausea','headache','low blood pressure','syncope'],
 'Additive CNS depression with other sedatives, benzodiazepines, and alcohol. Fewer drug interactions than cyclobenzaprine. Can discolor urine (brown/green — harmless).',
 'Centrally-acting muscle relaxant with fewer drug interactions than cyclobenzaprine. Fewer anticholinergic effects.',
 'Muscle spasm, tetanus (IV form)',
 '1500 mg four times daily initially, reduced to 750 mg four times daily for maintenance.',
 'No significant physiological withdrawal. Muscle spasms may return after stopping.',
 '["500 mg", "750 mg", "1000 mg"]'::jsonb),

('st. john''s wort', 'Herbal supplement', 300, 'mg', 24,
 ARRAY['photosensitivity','GI upset','dry mouth','dizziness','insomnia','anxiety','fatigue'],
 'Serious serotonin syndrome risk with SSRIs, SNRIs, and MAOIs. Potent CYP3A4 and P-glycoprotein inducer — significantly reduces levels of many medications including oral contraceptives, HIV medications, warfarin, cyclosporine, and antidepressants. Do not combine with any serotonergic drug.',
 'Herbal supplement commonly used for mild to moderate low mood. One of the most clinically significant herbal drug interactions due to broad enzyme induction.',
 'Mild to moderate depression (supplement, some evidence)',
 '300 mg three times daily (standardized to 0.3% hypericin).',
 'No physiological withdrawal at supplement doses. Mood effects may take weeks to resolve after stopping.',
 '["300 mg"]'::jsonb)

ON CONFLICT (name) DO UPDATE SET
  category                = EXCLUDED.category,
  common_dose             = EXCLUDED.common_dose,
  dose_unit               = EXCLUDED.dose_unit,
  typical_onset_hours     = EXCLUDED.typical_onset_hours,
  common_side_effects     = EXCLUDED.common_side_effects,
  notes                   = EXCLUDED.notes,
  purpose                 = EXCLUDED.purpose,
  conditions_treated      = EXCLUDED.conditions_treated,
  dosage_range            = EXCLUDED.dosage_range,
  discontinuation_notes   = EXCLUDED.discontinuation_notes,
  common_doses_list       = EXCLUDED.common_doses_list;
